name: WhatCrates
description: WhatCrates is customly made crates plugin for najeeslays
version: 2.0.0
author: SchdowNVIDIA
api: 3.9.3
main: SchdowNVIDIA\WhatCrates\Main

permissions:
  whatcrates:
    default: op
    description: WhatCrates command permission
